flux-iac/tofu-controller

controllers/tc000012_src_bucket_no_outputs_test.go
controllers/tc000190_unsupported_source_should_error_test.go
controllers/tc000191_missing_source_should_error_test.go

This PR add a few additional test cases covering the reconciler's `getSource` function, specifically:
- handling source of type `kind: Bucket`
- error handling for missing sources
- error handling for unsupported source

tests: Increase coverage for `getSource`

---

README.md
api/v1alpha1/terraform_types.go
config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
controllers/tc000200_disable_drift_detection_test.go
controllers/terraform_controller.go

This change introduces a new field `.spec.disableDriftDetection` which when `true` will bypass drift detection. Defaults to false.
This may be desirable when working with a complex state file or large Kubernetes cluster.
Example usage, disabling drift detection:
```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
name: helloworld
namespace: flux-system
spec:
approvePlan: "auto"
disableDriftDetection: true
path: ./
sourceRef:
kind: GitRepository
name: helloworld
namespace: flux-system
```
Implements #14 
Signed-off-by: Piaras Hoban <piaras@weave.works>

Support disabling drift detection

---

controllers/tc000010_no_outputs_test.go
controllers/tc000012_src_bucket_no_outputs_test.go
controllers/tc000030_plan_only_no_outputs_test.go
controllers/tc000050_plan_and_manual_approve_no_outputs_test.go
controllers/tc000100_applied_should_tx_to_plan_when_source_changed_test.go
controllers/tc000110_auto_applied_should_tx_to_plan_then_apply_when_source_changed_test.go
controllers/tc000130_destroy_no_outputs_test.go
controllers/tc000140_auto_applied_should_tx_to_plan_then_apply_when_drift_detected_test.go
controllers/tc000150_manual_apply_should_report_and_loop_when_drift_detected_test.go
controllers/tc000160_auto_applied_should_tx_to_plan_when_unrelated_source_changed_test.go
controllers/tc000210_plan_encode_decode_test.go
controllers/terraform_controller.go

Recreated PR for https://github.com/chanwit/tf-controller/pull/27 to fix bad rebase commit history.
This change introduces the ability to gzip encode larger than 1 MB plans so that they can still store as a secret.
Example usage:
```
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
name: helloworld
namespace: flux-system
spec:
approvePlan: "auto"
path: ./
sourceRef:
kind: GitRepository
name: helloworld
namespace: flux-system
```
I tested it locally as well and seem to be working as expected.
Related issue: https://github.com/chanwit/tf-controller/issues/12

Add gzip encoding annotation to tfplan secret and update tests

---

README.md

This is to add helm instructions. The chart artifacts are stored in https://github.com/tf-controller/charts. 
https://github.com/chanwit/tf-controller/issues/36

Add helm instruction

---

Makefile
controllers/suite_test.go
controllers/tc000140_auto_applied_should_tx_to_plan_then_apply_when_drift_detected_test.go
controllers/tc000160_auto_applied_should_tx_to_plan_when_unrelated_source_changed_test.go
controllers/tc000170_if_apply_error_we_should_delete_the_plan_and_start_over_test.go
controllers/tc000201_auto_approve_with_disabled_drift_detection_test.go
controllers/tc000220_support_config_file_via_secret_test.go
controllers/tc000230_drift_detection_only_mode_test.go
controllers/terraform_controller.go

This PR introduces the following changes in order to prepare the ground for test suite automation (#35) .
Items addressed are as follows:
- Increase global timeout to 30s to mitigate flaky asynchronous tests involving Terraform plan & apply operations
- Add environment variables to allow disabling Kubernetes and Terraform logs for more readable test output
- Update Makefile to use `go test -v ./controllers` so that test result output is streamed as the individual tests run (rather than at the end of the entire run).

Test Suite Cleanup

---

api/v1alpha1/terraform_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
controllers/tc000140_auto_applied_should_tx_to_plan_then_apply_when_drift_detected_test.go
controllers/tc000150_manual_apply_should_report_and_loop_when_drift_detected_test.go
controllers/tc000230_drift_detection_only_mode_test.go
controllers/terraform_controller.go
docs/api/terraform.md

This PR adds the following status fields to the Terraform resource:
-  `LastDriftDetectedAt`
-  `LastAppliedByDriftDetectionAt`
Also includes a fix for a sneaky variable shadowing problem in the drift detection code.
Fixes #7

Add Drift Detection Status Fields 

---

.github/workflows/scan.yaml

FOSSA scan is using WW account. When we decide where this project belongs to, we can update the token. 
Relates to https://github.com/chanwit/tf-controller/issues/47

Add FOSSA and CodeQL scan

---

.github/workflows/helm-release.yaml
.github/workflows/helm-test.yaml
.github/workflows/release.yaml
README.md
charts/tf-controller/.helmignore
charts/tf-controller/Chart.yaml
charts/tf-controller/README.md
charts/tf-controller/templates/_helpers.tpl
charts/tf-controller/templates/crds.yaml
charts/tf-controller/templates/deployment.yaml
charts/tf-controller/templates/rbac.yaml
charts/tf-controller/templates/serviceaccount.yaml
charts/tf-controller/values.yaml
ct.yaml

- move tf-controller chart from https://github.com/tf-controller/charts
- add chart test action
- add chart release action
- add chart as part of release step
Resolves https://github.com/weaveworks/tf-controller/issues/86
The release action pushes index.yaml and chart package to `gh-pages` branch. This requires github pages to be set up have the helm repository accessible. An issue is submitted to the organization admin. 

Move tf-controller chart

---

.github/workflows/e2e.yaml
DEVELOPMENT.md
Makefile
cmd/manager/main.go
config/manager/manager.yaml

While debugging, I found that the make targets used by e2e test were not using the latest image built. After fixing them, I uncovered two issues that weren't previously discovered. These issues are fixed in this PR. 
- The mtls certificate secret was using `flux-system` as its namespace. This could be problematic if the user does not have `flux-system` namespace and want to install in another namespace. This caused the controller in CrashLoopBackOff state with the following error.
```
{"level":"error","ts":"2022-02-10T21:22:23.106Z","logger":"setup","msg":"problem running manager","error":"creating secret to update certificates: namespaces \"flux-system\" not found","errorVerbose":"namespaces \"flux-system\" not found\ncreating secret to update …
```

Fix e2e make targets and issues uncovered

---

api/v1alpha1/terraform_types.go
config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
controllers/tc000121_destroy_on_delete_test.go
controllers/terraform_controller.go
docs/References/terraform.md
docs/use_cases.md

The resources created by terraform are not defaulted to destroyed after the object is deleted from the cluster. This feature adds `.spec.destroyResourcesOnDeletion` flag to enable this behavior. To enable destroy resources on object deletion, set `.spec.destroyResourcesOnDeletion` to `true`. 
```yaml
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
name: helloworld
namespace: flux-system
spec:
approvePlan: "auto"
destroyResourcesOnDeletion: true
path: ./
sourceRef:
kind: GitRepository
name: helloworld
namespace: flux-system
```
Addresses https://github.com/weaveworks/tf-controller/issues/96

Add .spec.destroyResourcesOnDeletion

---

controllers/terraform_controller.go
mtls/rotator.go

This PR use `<- mgr.Elected()` to block the cert rotation on other instances, so that the leader does so. 
Please note that `<-mgr.Elected()` gets closed only when the pod becomes the leader.
At the controller, instead of using the Ready ch, we read and validate the Cert secret directly. If it's not found, or invalid, we retry.
Fix #102

Rotate cert by leader only

---

Dockerfile

We no longer need the Terraform binary inside the controller image because it's now in the Runner Pod image.
Fix #109

remove the terraform binary from the controller image

---

cmd/manager/main.go
controllers/suite_test.go
mtls/rotator.go

This PR adds the ability to specify `--cert-validity-duration` and `--cert-rotation-check-frequency` flags on the controller to change the mTLS certificate validity duration and check frequency. 
Fix #125

Make cert rotation configurable

---

.github/workflows/e2e.yaml
.github/workflows/test.yaml
api/v1alpha1/terraform_types.go
cmd/manager/main.go
config/testdata/chaos/test.yaml
controllers/suite_test.go
controllers/tc000250_mtls_generate_creds_test.go
controllers/terraform_controller.go
mtls/grpc.go
mtls/rotator.go

Fixes #155 
This PR fixes the validation process of tlscert.
I removed batch pod deletion logic because it might accidentally delete long running pod of other TF objects.
We should let a TF object takes care of its own runner pod only.

use tlscert instead of cacert when validating cert of each pod

---

.github/workflows/e2e.yaml
api/v1alpha1/terraform_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
controllers/terraform_controller.go
docs/References/terraform.md

We got a bad side-effect of retaining runner pods after use, including a security concern, a TLS problem.
So a runner pod should be clean up by default.
Fixes #164

change the behaviour of pod clean up to be true by default

---

docs/use_cases.md

going through the docs atm, will update if I find anything more :smile: 
got this error when setting up the terraform resource using `0.7.0`:
```
wego-system   kind-kind-system   False   Terraform/wego-system/auto-apply-terraform dry-run failed, reason: Invalid, error: Terraform.infra.contrib.fluxcd.io "auto-apply-terraform" is invalid: spec.interval: Required value
```

Update use_case.md to include mandatory `interval` field

---

charts/tf-controller/Chart.yaml
charts/tf-controller/README.md
charts/tf-controller/templates/security-group-policy.yaml
charts/tf-controller/values.yaml

This change will allow setting up an [AWS EKS `SecurityGroupPolicy`](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#deploy-securitygrouppolicy) against the `ServiceAccount` used by the `tf-controller` `POD`s.
If supplied the `POD`s will be started and run under the specific AWS Security Groups that are passed in the list.

Setup a SecurityGroupPolicy

---

.github/workflows/scan.yaml

The current API token is linked to my personal account. Created a new one using corporate account and replacing it.

Update to use ww corporate FOSSA api token

---

.goreleaser.yml

This PR enables publishing `tfctl` releases to the weaveworks homebrew tap repository. 
Signed-off-by: Piaras Hoban <phoban01@gmail.com>

Publish `tfctl` releases to weaveworks/homebrew-tap

---

.github/workflows/scan.yaml
Makefile
runner.Dockerfile
utils/json_encode_bytes.go

- Change `go get` to `go install` due to [deprecation of 'go get' for installing executables](https://go.dev/doc/go-get-install-deprecation)
- Change `json_encode_bytes.go` to fix the error/fmt issue
- Updated `tf-runner` Terraform binary from `1.1.9` to `1.2.0`
- Updated CodeQL from `v1` to `v2`
- Other fixes as per below in PR commentary
NB: the `Terraform` binary will warn on a high severity CVE, this is a false positive. You can read more about the issue here: https://github.com/hashicorp/terraform/issues/30877

Go Get move to Go Install + Update of Error

---

cmd/runner/main.go
controllers/suite_test.go
controllers/terraform_controller.go
go.mod
runner/server.go

We enable info-level logs by default also for Runner.
To disable logging for Runner, set `DISABLE_TF_LOGS=1` to the runnerPodTemplate.
Also fixes: #203

replace logging lib in runner and display logging in runner console

---

runner/server.go

Fixes #239 
This commit disables sensitive logging by default.
By default Terraform logs are shown, but sensitive logs will be now displayed only when `ENABLE_SENSITIVE_TF_LOGS=1`.
If `DISABLE_TF_LOGS=1` the Terraform logging will be disabled entirely.

fix sensitive logging in runner

---

docs/use_cases.md

Annotating the controller does not expose the AWS credentials to the AWS Terraform provider. The credentials need to be provided on the runner.

Correct IRSA use case docs to annotate runner instead of controller

---

cmd/manager/main.go
controllers/terraform_controller.go
mtls/rotator.go

From pprof, we found a hidden race condition between assigning TLS for the runner and obtaining TLS for gRPC client.
```
549 @ 0x439b56 0x4498f2 0x88661b 0x880b55 0x89880c 0x8978b5 0x896f3f 0x896c4e 0x87a99d 0x87a885 0x14f160e 0x1685d6c 0x1683505 0x1681510 0x14159ef 0x1417a7e 0x14172c5 0x1416c85 0x46ae01
#	0x88661a	google.golang.org/grpc.(*pickerWrapper).pick+0x21a						/go/pkg/mod/google.golang.org/grpc@v1.45.0/picker_wrapper.go:103
#	0x880b54	google.golang.org/grpc.(*ClientConn).getTransport+0x34						/go/pkg/mod/google.golang.org/grpc@v1.45.0/clientconn.go:962
#	0x89880b	google.golang.org/grpc.(*clientStream).newAttemptLocked+0x84b					/go/pkg/mod/google.golang.org/grpc@v1.45.0/stream.go:410
#	0x8978b4 …
```

fixed a race condition that allows grpc client and the runner to use different secrets

---

tfctl/show_plan.go

Showing plan sometimes requires `terraform` to access the source code (https://github.com/hashicorp/terraform/issues/21966).
I'm unable to display plans without this fix, got:
```
Error: failed to parse Terraform plan: exit status 1
Error: Failed to load plugin schemas
Error while loading schemas for plugin components: 7 problems:
- Failed to obtain provider schema: Could not load the schema for provider
registry.terraform.io/gavinbunney/kubectl: failed to instantiate provider
"registry.terraform.io/gavinbunney/kubectl" to obtain schema: unavailable
provider "registry.terraform.io/gavinbunney/kubectl".
- Failed to obtain provider schema: Could not load the schema for provider
registry.terraform.io/hashicorp/aws: failed to instantiate provider
"registry.terraform.io/hashicorp/aws" to …
```

fix(tfctl): show plan current working directory

---

controllers/terraform_controller.go

Make the initialization status reported into the objects sooner than later.
Fixes #302 

fix initialization status

---

controllers/tc000010_no_outputs_test.go
controllers/tc000011_bad_tar_gz_no_outputs_test.go

Tests are very useful in addition to documents.
They can be examples for users on how to use the API.

start to use YAMLs in tests

---

controllers/tc000310_node_selector_affinity_tolerations_test.go

This PR:
- sets up the `Terraform` resources  in the `000310` tests using yaml strings rather than building up the object in Go.
- fixes the `000310` tests so that they are checking the generated `PodSpec` that the reconciler creates.
This break was called out in #331

Fix the test to actually test the selector changes

---

runner/server.go

Terraform has special handling of any configuration file whose name ends in `_override.tf` or `_override.tf.json`. This special handling also applies to a file named literally `override.tf` or `override.tf.json`.
By renaming `backendConfigPath` to `backend_override.tf` it'll allow `backendConfig.customConfiguration` to be set and overwritten as expected when a backend is already defined in the Terraform Module.
Fixes: #389

Replace backendConfigPath with Override Files format

---

charts/tf-controller/Chart.yaml
charts/tf-controller/README.md
charts/tf-controller/templates/runner-serviceaccount.yaml

Fixes the following issue:
```
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:\n  line 16: mapping key \"apiVersion\" already defined at line 2\n  line 17: mapping key \"kind\" already defined at line 3\n  line 18: mapping key \"metadata\" already defined at line 4
```

 Fix runner service account template not returning multiple documents when defining allowedNamespaces

---

charts/tf-controller/Chart.yaml
charts/tf-controller/README.md
charts/tf-controller/templates/deployment.yaml

This makes sure that all types != string will be quoted by Helm.

enforcing quotes for extraEnv

---

charts/tf-controller/Chart.yaml
charts/tf-controller/README.md
charts/tf-controller/templates/deployment.yaml
charts/tf-controller/values.yaml

We're running into kube client rate-limiting errors due to which the TLS secret creation fails, thus causing the `runner` pod to go into `CrashLoopBackoff`
```
kubectl logs -f demo-workload-6x7k1b-tf-runner
2022/12/09 00:08:28 Starting the runner... version sha
I1209 00:08:29.652396 7 request.go:682] Waited for 1.03721706s due to client-side throttling, not priority and fairness, request: GET:
[https://10.100.0.1:443/apis/certificates.k8s.io/v1?timeout=32s](https://10.100.0.1/apis/certificates.k8s.io/v1?timeout=32s)
2022/12/09 00:08:30 secrets "terraform-runner.tls-1671035316" not found
```
We were able to fix this manually by setting the `kube-api-qps` and `kube-api-burst` flags, but these are not exposed to us via the helm chart

add support to set kube client config flags

---

charts/tf-controller/Chart.yaml
charts/tf-controller/README.md
charts/tf-controller/values.yaml

As per the discussion in #479 , the recommendation for a single replicaCount is outdated. Users are encouraged to use multiple replicas of tf-controller

[helm] update docs on replicaCount

---

charts/tf-controller/Chart.yaml
charts/tf-controller/README.md
charts/tf-controller/templates/deployment.yaml

This lead to invalid YAML because when set the resulting labels would format to something like this:
```yaml
labels:
customlabel: test
selectorlabel: test
```

Selector labels and custom labels had different indentation

---

.github/workflows/test.yaml
runner-azure.Dockerfile
runner.Dockerfile

Hello!
I'm in need of OIDC support using the AzureRM Backend which was released in Terraform version v1.3.4. 
Hopefully it is enough to just bump the version. Let me know if I need to update anything else.

chore(tf-version): bump from 1.3.1 to 1.3.7

---

docs/use_tf_controller/with_GitOps_dependency_management.md

You can see the effects of the unclosed codeblock here:
https://weaveworks.github.io/tf-controller/use_tf_controller/with_GitOps_dependency_management/

Fix error in docs examples

---

config/samples/infra_v1alpha1_terraform.yaml
config/samples/infra_v1alpha2_terraform.yaml
docs/getting_started.md
docs/rc.yaml
docs/release.yaml

Changes:
- Switch the v0.15.0-rc.1 Helm installer to OCI HelmRepository
- Bump Flux APIs
- Add proper sample config

Update Flux APIs and use OCI HelmRepository

---

rfcs/DECISION_MAKING.md
rfcs/README.md
rfcs/RFC-0000/README.md

Our goal in this PR is to institute an RFC (Request for Comments) process, drawing inspiration from the existing Flux's v2 RFC framework.
Upon successful implementation of this process, we will proceed to address the considerations outlined in issue #595 via a comprehensive RFC.
According to the RFC process, a proposal can only be merged after it has been approved by either
- **two project maintainers**, or
- **one project maintainer and one individual from the following**: a Weaveworks Tech Lead, a Weaveworks Product Manager, or a Weaveworks Principal Engineer.
Fixes #602

Establishing an RFC Process

---

rfcs/0001-polling-mechanism/README.md

This RFC proposes a polling mechanism as a secure and portable solution for tracking changes in the
Branch-based Planner with GitHub. The proposed system reduces security risks associated with webhooks, which require
exposing a publicly accessible endpoint by having the Kubernetes cluster periodically query GitHub for changes.
Fixes #595 
Per the RFC process, the proposal can only be merged after it has been approved by either
-  two project maintainers, or
-  one project maintainer and one individual from the following: a Weaveworks Tech Lead, a Weaveworks Product Manager, or a Weaveworks Principal Engineer.

RFC-0001 Polling mechanism for the branch-based planner

---

cmd/branch-based-planner/main.go
internal/git/provider/github_provider.go
internal/git/provider/provider.go
internal/git/provider/pull_request.go
internal/git/provider/repo.go
internal/informer/bbp/main.go
internal/server/webhook/options.go
internal/server/webhook/server.go

What it does:
Implements a simplified version of the informer to watch Terraform objects and detect if we have new Plan output available, then publish it as a comment on a PR.
What it doesn't do:
* Deeper filtering for example "is the plan still has mark it's pending".
* The "publish comment" part is a dummy interface. It will be mostly code from WGE with multiple git providers[^1], and just add missing behaviour.
[^1]: https://github.com/weaveworks/weave-gitops-enterprise/tree/main/pkg/git
Closes #605
References:
* https://github.com/weaveworks/weave-gitops-enterprise/tree/main/pkg/git

feat: detect terraform object changes and publish generated plans

---

controllers/tc000260_runner_pod_test.go
controllers/tf_controller.go
controllers/tf_controller_runner.go

closes #547 
- Setting the `app.kubernetes.io/instance` label to `tf-runner-<short-rev>` to avoid hitting label size limits
- Fixing some tests assertions

Setting up instance label for Runner pods

---

runner/server.go
runner/server_plan.go
runner/server_save_tfplan.go
runner/server_show_plan.go

Fixes #637
Backport to v0.14.3 in #643

fix logging in tf-runner

---

cmd/manager/main.go
controllers/tc000015_source_cross_ns_denied_test.go
controllers/tf_controller.go

The Flux convention is to use the flag --no-cross-reference-refs (as encoded in github.com/fluxcd/pkg/acl) to deny cross-namespace references, thereby closing a potential security hole.
This commit adds support for the flag to the controller, and a test that it does indeed ban cross-namespace refs.

Add --no-cross-namespace-refs to tf-controller

---

cmd/branch-based-planner/main.go

When using github.com/fluxcd/pkg/runtime/logger, the advice is to call `SetLogger()` as soon as you've constructed a log. Doing so avoids a panic from controller-runtime, which complains its own `SetLogger` was not called.
This appears -- admittedly, with very few data points -- to be less of a problem prior to #672. I'm not sure why, possibly there is a race between something provoking controller-runtime to sort itself out. I'm not too bothered finding out why, this time, because calling `SetLogger(...)` early and explicitly is better in any case.

Use SetLogger early in branch-based-planner/main.go to avoid a (near) panic

---

internal/server/polling/main_test.go
internal/server/polling/poll_test.go
internal/server/polling/server.go

This adds a bit of scaffolding so that the branch-planning can be tested with
- a real Kubernetes API (via envtest)
- a fake git provider (via an option for injecting it when constructing the Server)
It also gives an example of testing the base case.

Branch-planning test scaffold

---

api/planid/plain_id.go
api/planid/plan_id_test.go
api/v1alpha2/terraform_types.go
controllers/tc000010_no_outputs_test.go
controllers/tc000011_workspace_no_outputs_test.go
controllers/tc000012_src_bucket_no_outputs_test.go
controllers/tc000030_plan_only_no_outputs_test.go
controllers/tc000031_plan_only_with_showplan_as_cm_no_outputs_test.go
controllers/tc000050_plan_and_manual_approve_no_outputs_test.go
controllers/tc000051_plan_and_manual_approve_and_replan_no_outputs_test.go
controllers/tc000052_plan_and_manual_approve_with_files_test.go
controllers/tc000100_applied_should_tx_to_plan_when_source_changed_test.go
controllers/tc000110_auto_applied_should_tx_to_plan_then_apply_when_source_changed_test.go
controllers/tc000121_destroy_on_delete_test.go
controllers/tc000130_destroy_no_outputs_test.go
controllers/tc000131_destroy_no_changes_test.go
controllers/tc000140_auto_applied_should_tx_to_plan_then_apply_when_drift_detected_test.go
controllers/tc000150_manual_apply_should_report_and_loop_when_drift_detected_test.go
controllers/tc000160_auto_applied_should_tx_to_plan_when_unrelated_source_changed_test.go
controllers/tc000201_auto_approve_with_disabled_drift_detection_test.go
controllers/tc000220_support_config_file_via_secret_test.go
controllers/tc000241_auto_approve_with_health_checks_test.go
controllers/tc000280_inventory_test.go
controllers/tc000290_force_unlock_test.go
controllers/tc000350_depends_on_test.go
controllers/tf_controller_plan.go
runner/server.go
runner/server_save_tfplan.go

Fixes #599
Fixes #699 
To cope with similar issues in the future, we'll use the short plan id everywhere.
- In the pending plan 
- In the last applied plan
- In the approval message
- Having a dedicated lib for converting a revision to a plan id, in `api/planid/plan_id.go` and having test cases to cover old and new formats.

fix pending plan not equal plan id in secret

---

controllers/tf_controller.go
controllers/tf_controller_finalizer.go

finalize() routine updates terraform.Status.Lock.Pending in terraform CR on lock error.
Return updated terraform from routine finalize() so that it can be patched on lock error.
closes #560

patch: fix force-unlock with delete path by updating in terraform.Status.Lock.Pending terraform CR.

---

config/tilt/test/tf-dev-subject.yaml
controllers/tc000290_force_unlock_test.go
controllers/tf_controller.go
runner/server_plan.go
runner/server_plan_test.go

This PR introduces a log sanitization mechanism in the tfPlan function of the tf-runner. The new function, `sanitizeLog`, scans logs for JSON objects in certain lines. It replaces all values in these JSON objects with asterisks to hide potentially sensitive data.
Then `tfPlan` has been modified to use `sanitizeLog` function. It discards standard output and captures standard error into a buffer for sanitization. If an error occurs, `sanitizeLog` is used to sanitize both the stderr output and the error message.

sanitize plan logs

---

docs/References/terraform.md

This fixes a discrepancy in the docs per https://github.com/weaveworks/tf-controller/issues/684 where the enum of the storeReadablePlan variable doesnt render in the documentation, leading the user to misunderstand what is available and applicable

fix storeReadablePlan Enum variable in docs

---

tfctl/main.go

Fixes #357 
This PR unblocks users and enables them to utilize the break-the-glass feature properly.
It resolves an issue where our program failed to find an OpenID Connect (OIDC) authentication provider, resulting in an error "no Auth Provider found for name 'oidc'".
To address this, I have added a blank import for the `k8s.io/client-go/plugin/pkg/client/auth` package in tfctl `main.go` file. This import ensures that the necessary authentication plugins, including the OIDC plugin, are registered during the program's initialization.
This is how the fix works:
- The Go runtime imports all packages specified in the tfctl `main.go` file, including `k8s.io/client-go/plugin/pkg/client/auth`.
- During the import process, it is executed if an `init()` function exists in the auth package.
- The …

import client-go auth plugin for oidc

---

.github/workflows/test.yaml
Makefile
cmd/branch-based-planner/flags.go
cmd/branch-based-planner/polling.go
controllers/tf_controller_finalizer.go
internal/informer/bbp/informer.go
internal/server/polling/option.go
internal/server/polling/poll_test.go
internal/server/polling/server.go
internal/server/polling/terraform.go

Closes https://github.com/weaveworks/tf-controller/issues/662
Closes https://github.com/weaveworks/tf-controller/issues/586
- Added the `createTerraform`, `createSource`, `createLabels`, and `createObjectName` methods.
- Added the `listTerraformObjects` method.
- Added the `deleteTerraform` and `deleteSource` methods.
- Reworked branch-based planner label keys and values.
- Added the `branchPollingInterval` flag.
- Added Terraform object and source reconciliation logic.
- Added the `reconcileTerraform` and `reconcileObjects` functions for Terraform object and source reconciliation.
- Added tests for creating, updating, and deleting objects during polling
- Added a new test target to run tests in the `internal` directory.
- Added running internal tests to the `test` workflow.

Handle the list of Pull Requests

---

.github/workflows/e2e.yaml
.github/workflows/test.yaml

The test and e2e test workflows can run for 20-30 minutes and they use a lot of resources. If a commit/pull request contains only docs changes, it's a waste of time and resources.
`charts/**` can be ignored for tests, but not for e2e tests because that workflow uses helm charts.
Closes #688
References:
* https://github.com/weaveworks/tf-controller/issues/688

chore(ci): do not run test and e2e test when there are no code changes

---

config/tilt/test/tf-dev-subject.yaml
controllers/tf_controller_runner.go
mtls/rotator.go
tfctl/replan.go
tfctl/show_plan.go

Fixes #737 
Fixes #709 
Fixes #657
There are two cases
1. Replan request timed out. This error was caused by a race condition during the controller restart & the recreation of new runners.
2. `tfctl replan` is working fine. This PR fixes only the display message.
** Fix for case no 1**
Simply by checking the Secret, if not found re-create it.
**Fix for case no 2** 
Previous message:
```
❯ tfctl get
NAMESPACE       NAME            READY   MESSAGE                                                 PLAN PENDING    AGE       
flux-system     helloworld-tf   Unknown Plan generated: This object is in the plan only mode.   true            2 minutes
❯ tfctl replan helloworld-tf
 Replan requested for flux-system/helloworld-tf
Changes to Outputs:
+ hello_world = "Hello Plan plan, test!"
You can apply …
```

fix tfctl message when we're in the plan only mode

---

internal/server/polling/poll_test.go
internal/server/polling/terraform.go

When cloning Terraform objects as Branch Planner Terraform objects, `approvePlan` has to be empty and `force` has to be `false` because they have no value, but they can mess up complext state-machine of the controller.
Closes #751
References:
* https://github.com/weaveworks/tf-controller/issues/751

feat: set approvePlan to be blank and force to be false

---

Makefile

With `go run`, it's still beneficial to get BuildSHA. With this information when we share logs with others we can verify it's on the latest commit on main, or we can simply checkout that specific commit to see if we can reproduce an issue. We can ask for this, but if it's already in the copied logs, we don't have to ask.
Command:
```
make run-planner
```
Output:
```json
{"level":"info","ts":"2023-07-11T15:32:28.249+0200","logger":"informer","msg":"Starting branch-based planner informer","version":"v0.15.1","sha":"5a2d800"}
{"level":"info","ts":"2023-07-11T15:32:28.249+0200","logger":"polling-server","msg":"Starting polling server","version":"v0.15.1","sha":"5a2d800"}
{"level":"error","ts":"2023-07-11T15:32:28.256+0200","logger":"informer","msg":"branch-based planner informer …
```

refactor: add build sha and version to go run tasks

---

api/v1alpha2/terraform_types.go
cmd/branch-planner/informer.go
internal/config/config.go
internal/config/config_test.go

These are just some things I noticed looking at PRs.
- configmap.Data is a map and can be nil, so check for that to avoid an NPE, and check the expected field is there so it can fail there and then rather than more mysteriously and later
- be more precise when parsing an object key from a string
- remove a bunch of unnecessary notation that made me have to pause and figure out why it was there. I still don't know, but it's not necessary, so to save the next person trying to figure it out, ...

Improving ConfigMap Handling and Parsing Object Key, Removed Redundant Notation for the Controller and the Branch Planner

---

internal/config/config.go
internal/server/polling/config.go

The branch planner program would run inside `flux-system` by default, so configuration is assumed to be read from the `flux-system` instead of `default`.
Closes #760
References:
* https://github.com/weaveworks/tf-controller/issues/760

patch: use "flux-system" namespace instead of "default" for config

---

cmd/branch-planner/informer.go
internal/config/config.go
internal/informer/branch-planner/informer.go
internal/informer/branch-planner/informer_test.go
internal/server/polling/server.go
internal/server/polling/terraform.go

Currently we have exact definition for resources. To make it easier to use if `name` is not defined in the ConfigMap for a resource, polling will be used on all Terraform objects in the defined namespace.
Example config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: branch-based-planner
data:
secretMamespace: flux-system
secretName: bbp-token
resources: |-
- namespace: flux-system
```
Logging:
```json
{"level":"info","ts":"2023-07-11T17:59:42.065+0200","logger":"informer","msg":"Starting branch-based planner informer","version":"v0.15.1","sha":"87527a4d9e8643167909e71b855a22062ba9c41b"}
{"level":"info","ts":"2023-07-11T17:59:42.066+0200","logger":"polling-server","msg":"Starting polling server","version":"v0.15.1","sha":"87527a4d9e8643167909e71b855a22062ba9c41b"} …
```

feat: support watching all Terraform objects in namespace

---

runner/server.go
runner/server_load_tfplan.go
runner/server_load_tfplan_test.go

Fixes #745
In response to user feedback, we are implementing a fix where the plan annotation check is bypassed if in force mode. This update is intended to mitigate the prevalent issue experienced by many users who were struggling with the Terraform controller bug. This bug was caused by a failure in parsing of the Flux revision format change from v0.41 to v2, and many users thought that changing `force: true` would forcefully apply the plan regardless and no error.

if force mode is true, we skip the plan annotation check

---

Dockerfile
cmd/branch-planner/flags.go
internal/config/config.go
internal/config/config_test.go
internal/server/polling/config.go
planner.Dockerfile
runner-azure.Dockerfile
runner.Dockerfile

If `RUNTIME_NAMESPACE` is not defined, it falls back to `flux-system`.
Closes #765
Closes #767
References:
* https://github.com/weaveworks/tf-controller/issues/765

feat: use RUNTIME_NAMESPACE for resources if namespace is not defined

---

docs/branch_based_planner/getting-started.md

Tried to explain most of the steps, but intentionally did not add docs about how to configure the tf-controller itself and set it as a pre-requirement.
I'm not sure it satisfies #783 or not, but it's related to that issue.
Related to #783
References:
* https://github.com/weaveworks/tf-controller/issues/783

docs: getting started with branch planner

---

cmd/branch-planner/flags.go
cmd/branch-planner/polling.go
internal/server/polling/option.go
internal/server/polling/server.go
internal/server/polling/terraform.go

The standard for Flux-source-integrating controllers is to include a flag `--no-cross-namespace-refs` for disabling cross-namespace access to sources. This commit adds the flag, and implements the ban when it's set.
This also fixes a bug whereby the namespace of the sourceRef was not defaulted to the namespace of the Terraform object containing it; so, if you left it out, the client.Get() for the source would fail.

Add --no-cross-namespace-refs to branch-based-planner

---

docs/adr/0002-deny-cross-ns-by-default.md

This PR introduces a decision record for changing the default treatment of cross-namespace references, which appear in a couple of places in the API.
This is a reversal of the (implicit) decision to respect cross-namespace references by default, so deserves to be recorded.

Document ADR for denying cross-ns refs by default

---

charts/tf-controller/templates/planner-deployment.yaml
cmd/branch-planner/flags.go
internal/server/polling/option.go
internal/server/polling/server.go

If a Terraform resources is not in a namespace defined in the allowedNamespaces list, it will never be reconciled as the runner has no permissions in that namespace.
If someone creates a Terraform object in a "forbidden" namespace and configures that namespace to be watched by the Branch Planner, it would create new Terraform resources for each pull request, but none of them would be ever reconciled. If a repository has 10-20 open pull requests already, then we would create 10-20 dead Branch Planner Terraform objects with corresponding Secret and Source. That's a huge waste of resources.
This patch aims to fix this by using the same allowedNamespaces list.
closes #804
References:
* https://github.com/weaveworks/tf-controller/issues/804

patch: use allowedNamespaces in Branch Planner

---

charts/tf-controller/templates/planner-deployment.yaml

Branch Planner is not scalable yet. If someone tries to scale it, then they will see unexpected behavior.
Closes #807
References:
* https://github.com/weaveworks/tf-controller/issues/807

patch: static replica count for branch planner

---

Dockerfile
planner.Dockerfile
runner-azure.Dockerfile
runner.Dockerfile

Since Alpine 3.16, this is included within the base image and thus no longer required.
Refer to https://git.alpinelinux.org/aports/commit/?id=348653a9ba0701e8e968b3344e72313a9ef334e4 for more information.

build: remove `nsswitch.conf` creation

---

api/v1alpha1/terraform_types.go
charts/tf-controller/templates/crds.yaml
config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml

We changed `v1alpha1` in v0.14 to backport the break-the-glass feature, but the added fields don't exist in v0.15+ for `v1alpha1` and that can break upgrade processes.
Closes #866
References:
* https://github.com/weaveworks/tf-controller/issues/866
* https://github.com/weaveworks/tf-controller/pull/855

patch: back-backport v0.14 break-the-glass changes

---

.github/workflows/ossf.yaml

Relates to: https://github.com/weaveworks/tf-controller/issues/859
Configured to run:
- when the branch protection rule for the default branch changes
- when pushing to main
- every Saturday morning
- on demand (so that we can invoke it for testing)

ci: Add OpenSSF Scorecard GH Action

---

.github/workflows/verify.yaml
Makefile
docs/References/terraform.md

Relates to #859 
Added a new make target that invokes `go vet` and a CI workflow to call that target.

ci: Run `go vet` on CI

---

tfctl/install.go

Hi, I'm trying to fix `tfctl install --export` so I can deploy tf-controller via plain k8s manifests, like Flux (vs the HelmRelease offered in the guides).
After fixing this `---` issue this is the only error left:
```
➜  tf-controller git:(fix-tfctl-install) ✗ k apply -f tfctrl.yml
serviceaccount/tf-controller unchanged
serviceaccount/tf-runner unchanged
role.rbac.authorization.k8s.io/tf-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/tf-manager-role configured
clusterrole.rbac.authorization.k8s.io/tf-runner-role unchanged
rolebinding.rbac.authorization.k8s.io/tf-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/tf-cluster-reconciler unchanged
clusterrolebinding.rbac.authorization.k8s.io/tf-manager-rolebinding unchanged …
```

fix tfctl install --export not separating yaml objects properly

---

controllers/cleaner_test.go
controllers/tc000010_no_outputs_test.go
controllers/tc000011_bad_tar_gz_no_outputs_test.go
controllers/tc000011_workspace_no_outputs_test.go
controllers/tc000020_with_workspace_no_outputs_test.go

1. It used the same resource name as 000010 test.
2. We requested resources to be deleted, but we didn't wait them to be deleted.
fixes #908
References:
* https://github.com/weaveworks/tf-controller/issues/908

fix: 000011_workspace_no_outputs_test test

---

DEVELOPMENT.md

This is part of the requirements to get a passing OpenSSF badge.
Related to #859

docs: Add information on how to provide feedback and contribute

---

cmd/branch-planner/flags.go
cmd/branch-planner/polling.go
cmd/manager/main.go

With reference to [ADR 002](https://github.com/weaveworks/tf-controller/blob/main/docs/adr/0002-deny-cross-ns-by-default.md):
This adds the flag --allow-cross-namespace-refs, which defaults to `false` (do not allow cross namespace refs), and overrides the flag `--no-cross-namespace-refs` which is borrowed from Flux.
The rationale is that it's secure by default to not allow cross-namespace refs, and to make people explicitly allow them with the flag. It's early enough in the life of tf-controller to make this breaking change -- people using cross-namespace refs will just need to add the flag into their config.
Since people may already be using the flag `--no-cross-namespace-refs`, I've kept it. If `--allow-cross-namespace-refs` _is not_ supplied, and `--no-cross-namespace-refs` _is_ …

Add flag --allow-cross-namespace-refs to tf-controller and branch-planner

---

.github/workflows/targeted-test.yaml
.github/workflows/test.yaml

Benefits:
- Easier to re-run failed jobs, it does not re-run all of them
- Each group has it's own envtest
- Because it's parallel, it's faster (see comment)
related to #865

experiment: break up test jobs

---

controllers/tc000040_controlled_outputs_test.go
controllers/tc000041_all_outputs_test.go
controllers/tc000042_output_name_contains_dot_test.go
controllers/tc000043_controlled_outputs_should_be_reconciled_test.go
controllers/tc000044_plan_only_mode_test.go

They passed constistently running them 3 times in a row without break, so no main suit cleanup.
```
❯ go test ./controllers -parallel 1 -count=3 -test.run Test_00004
ok      github.com/weaveworks/tf-controller/controllers 22.412s
```
Fixes #904
References:
* https://github.com/weaveworks/tf-controller/issues/904

fix: controllers/tc00004x tests

---

controllers/tc000050_plan_and_manual_approve_no_outputs_test.go
controllers/tc000051_plan_and_manual_approve_and_replan_no_outputs_test.go
controllers/tc000052_plan_and_manual_approve_with_files_test.go
controllers/tf_controller.go

fix: controllers/tc00005x tests
Closes #905
---
fix: reconcile stuck in a loop with manual approval
After a bit of poking, if I remove all changed from the commit, except
the `patcher := ...` and the `patcher.Patch` call (so the
`finalizeStatus` does literally nothing, but patches the "expected
nothing"), it still causes an issue.
If I keep everything from the commit, but move the `patcher :=` line
into the `defer` function, tests are happy.
We already have status patching everywhere (without this commit
everything worked). The Patcher in this commit should just patch the
diff calculated in finalizeStatus.
I assume it a weird issue how the whole codebase tosses around the
`&terraform` reference and makes Patch calls somewhere else in the State
Machine.
Closes #890

fix: controllers/tc00005x tests and the manual approval stuck in loop bug

---

controllers/tc000120_delete_test.go
controllers/tc000121_destroy_on_delete_test.go
controllers/tc000130_destroy_no_outputs_test.go
controllers/tc000131_destroy_no_changes_test.go

```
❯ go test ./controllers -parallel=1 -count=3 -test.run="Test_0001[23]"
ok      github.com/weaveworks/tf-controller/controllers 118.087s
```
Fixes #945
References:
* https://github.com/weaveworks/tf-controller/issues/945

fix: controller 12x and 13x tests

---

controllers/cleaner_test.go
controllers/tc000201_auto_approve_with_disabled_drift_detection_test.go

```
❯ go test ./controllers -parallel=1 -count=3 -test.run="Test_000201"
ok      github.com/weaveworks/tf-controller/controllers 99.224s
```
For the cleanup:
Sadly `resource.GetObjectKind().GroupVersionKind().Kind` is an empty string, so it didn't work at all.
Fixes #947
References:
* https://github.com/weaveworks/tf-controller/issues/947

fix: controller test 201 and fix test clean-up

---

controllers/tc000230_drift_detection_only_mode_test.go

```
❯ go test ./controllers -parallel=1 -count=3 -test.run="Test_000230"
ok      github.com/weaveworks/tf-controller/controllers 41.527s
```
Fixes #948
References:
* https://github.com/weaveworks/tf-controller/issues/948

fix: controller test 230

---

Tiltfile
docs/branch_planner/least-required-permissions.md

The documentation said the token needs RW on Issues and R is enough on PullRequests, but in reality Issues are irrelevant, and RW is required for PullRequests.
Fixes #965
References:
* https://github.com/weaveworks/tf-controller/issues/965

docs: update least required permissions for a github api token

---

controllers/tc000240_health_check_test.go
controllers/tc000241_auto_approve_with_health_checks_test.go
controllers/tc000242_bad_health_checks_test.go

```
❯ go test ./controllers -parallel=1 -count=3 -test.run="Test_00024"
ok      github.com/weaveworks/tf-controller/controllers 13.980s
```
I tried to remove all external calls from health check, but I couldn't because for 240, it said it can't parse `server.Addr()` as health check. For 241, it's hardcoded in the terraform file and the test server is dynamic.
It can still be flaky if it can't reach "weave.works" or the server rejects the request because of too many requests, or any other reasons.
For now, I think it's not an issue. If it will be, we have to spend some (a bit more) time on it, as it's not trivial to update those values.
Closes #949
References:
* https://github.com/weaveworks/tf-controller/issues/949

fix: controller test 24x

---

local-e2e.sh

A small fix that adds `set -e` to the local e2e script to fail fast.

add set -e to the local e2e script

---

charts/tf-controller/templates/crds.yaml

We implemented addition fields to the Pod Spec but haven't added them to the Chart template yet.
This PR is a follow-up to fix that.
How I did:
`make release-manifests`
Then diff between the generated CRDs and the Helm CRDs template.

add missing pod spec CRDs to the chart template

---

controllers/tc000015_cliconfigsecret_cross_ns_denied_test.go
controllers/tf_controller_backend.go

This is another place that a cross-namespace ref can be supplied. This I learned: corev1.SecretReference has a namespace field.
Fixes #957.

Screen cross-ns refs in .spec.cliConfigSecretRef

---

charts/tf-controller/README.md
charts/tf-controller/README.md.gotmpl
docs/how_to/index.md
docs/how_to/use-cross-namespace-refs.md

Explains that cross-namespace refs are not allowed by default, and how to allow them.
I wanted to mention when cross-namespace refs started being disallowed by default, so I guessed at when it would appear in a release -- version >0.16, since it would indicate a minor version bump at least.
Fixes #956.

Explain `allowCrossNamespaceRefs` in chart README and docs/howto/

---

.github/workflows/e2e.yaml
config/testdata/drift-detection/test.yaml
local-e2e.sh

This change correct to behaviour of the drift e2e test case to:
- start with the auto mode and wait for the object applied state
- patch the object to be approvePlan: disable
- the object shoud continue to do drift detection correctly

correct the behaviour of e2e tests

---

.github/workflows/build-and-publish.yaml
.github/workflows/flaky.yaml
.github/workflows/targeted-test.yaml
.github/workflows/test.yaml
.github/workflows/verify.yaml
Makefile

Options I considered:
- Add a `testcase` build tag and use that to separate the two.
- Add skip option to the `target-test` target.
- Add create a new independent make target just to run those tests.
Dropped the idea to add build tag because ideally all of them should be easily executed locally without knowing you have to add `-tag testcase` to the command.
Dropped the skip option to `target-test` because that would make that way too complex, complex shell scripting in Makefiles can be fine, but I prefer not to do that. To create a separate shell script just for that, I didn't feel it's worth it.
At the end, I created a new `normal-controler-test` make target. The name is sketchy, but I couldn't come up with a better one, normal because it's not "test case based".
Fixes #981
References:
* …

tests: run non-numbered tests as part of the github workflow

---

controllers/tc000260_runner_pod_test.go

```
❯ go test ./controllers -parallel=1 -count=3 -test.run="Test_000260"
ok      github.com/weaveworks/tf-controller/controllers 85.192s
```
I set `Test_000260_runner_pod_test_env_vars_provider_vars_without_value` to be skipped because I couldn't make it pass consistently. It's still there, someone can jump on it and try, but I couldn't.
Fixes #950
References:
* https://github.com/weaveworks/tf-controller/issues/950

fix: controller test 260

---

controllers/tc000020_with_backend_no_outputs_test.go
controllers/tc000020_with_workspace_no_outputs_test.go

Somehow we missed this tone earlier.
```
❯ go test ./controllers -parallel=1 -count=3 -test.run="Test_000020"
ok      github.com/weaveworks/tf-controller/controllers 12.239s
```
Related to #865
References:
* https://github.com/weaveworks/tf-controller/issues/865

fix: controller test 20

---

.github/workflows/build-and-publish.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/helm-release.yaml
.github/workflows/helm-test.yaml
.github/workflows/ossf.yaml
.github/workflows/release-runners.yaml
.github/workflows/release.yaml
.github/workflows/scan.yaml
.github/workflows/targeted-test.yaml
.github/workflows/test.yaml
.github/workflows/verify.yaml

Pinning GH Actions version in order to address code scanning warnings.
Related to #991

ci: Pinned checkout and setup-go GH actions to commit hashes

---

internal/server/polling/poll_test.go
internal/server/polling/terraform.go

Fixes #915
This PR excludes the branch name from the object name because:
1. A branch name is possible to contain slash (`/`) or underscore (`_`) which are invalid for a Kubernetes object name.
2. We already use PR ID as part of the identifier. PR number is sufficient to make the object name unique.

exclude branch from create object name function

---

.github/workflows/blocked-reminder.yaml
.github/workflows/build-and-publish.yaml
.github/workflows/helm-release.yaml
.github/workflows/ossf.yaml
.github/workflows/release-runners.yaml
.github/workflows/release.yaml

Pin GitHub Actions versions to commit SHAs to address code scanning warnings (see example https://github.com/weaveworks/tf-controller/security/code-scanning/10)
Related to #991

ci: Pinned GH actions to commit hashes

---

.github/workflows/docs.yaml

The previous PR broke the docs workflow, this PR should fix it.

fix: Use write permissions when pushing Helm docs

---

internal/server/polling/poll_test.go
internal/server/polling/server.go
internal/server/polling/terraform.go

Fixes #898 
This PR contains two commits.
1. The first commit fixed the Terraform deletion logic
of the Branch Planner by making sure that the
Terraform object is deleted before the source.
It also changed the plan object creation logic by
making sure that
- the plan object won't delete the live resources.
- the plan object won't create any output secrets.
2. There was a bug inside the createLabels function
that modified the labels of the original objects
instead of creating a new map. The second commit fixed it.

Deleting the Terraform object before deleting its source

---

internal/server/polling/poll_test.go
internal/server/polling/terraform.go

A previous fix removed the branch name out of the object name, making
the object name harder to read. For example `hello-tf` became `hello-tf-1`.
This PR added the `pr` string to the suffix, resulting in the object
name `hello-tf-pr-1`. This makes it easier to discern that this object
corresponds to Pull Request 1 for example.
Fixes #1000 
Must merge after #1001

Add the `pr` string to suffix

---

internal/informer/branch-planner/informer_test.go
internal/informer/branch-planner/main_test.go
internal/server/polling/main_test.go
internal/server/polling/poll_test.go

Gomega doesn't have a function to mark a function as a test helper function. The built-in `testing` package has a `t.Helper()` function that marks the function as a test helper and when it prints out where the error happened, it will skip that function.
These test helper functions were added when I asked to not use dot import (I still against using it). I don't think the wrapper functions make it much easier to write and read tests then aliasing the gomega module, but I was much happier with it then dot importing it. However it caused problems debugging failed test because the failed test reported back the issue is in `main_test.go:LINE`, which is not very helpful:
```
main_test.go:74:
Expected
<string>: true
to equal
<string>:
```
In my opinion we should just simply use `gom` alias (or …

refactor: add testing.T to gomega wrapper functions

---

internal/server/polling/main_test.go
internal/server/polling/poll_test.go
internal/server/polling/terraform.go

By default the `SecretSuffix` is set to the name of the Terraform
resource, because of this, if it's not set on the original Terraform
resource, it's not set on the cloned one with Branch Planner. As a
result, the Branch Planner resource uses a separate state file.
This small patch makes sure the cloned object uses the same statefile
secret.
Fixes #1021
References:
* https://github.com/weaveworks/tf-controller/issues/1021

fix: branch planner does not use the original state file

---

docs/adr/0003-workspace-blob-caching.md

propose adr 0003 for workspace blob caching

---

MAINTAINERS

Makes Luke, Tom, and Piaras "emeritus maintainers" as their availability has changed. All have granted consent.

Updates maintainers file

---

DEVELOPMENT.md
Makefile
cmd/tfctl/main.go
tfctl/break_glass.go
tfctl/main.go

fixes #1097
As I said in #1097, break-glass could easily target the wrong cluster. This happened to me.
This PR adds the flags to the command, that should be passed and can be passed according to `tfctl help`.
Please try to get it into 0.16.0, so the fix gets out fast.

Fix break glass command; respect all flags

---

docs/rc.yaml

Fixes [rc.yaml](https://raw.githubusercontent.com/weaveworks/tf-controller/main/docs/rc.yaml) to point to latest RC.

docs: Bump version in manifest used in user guide to reflect latest RC

---

internal/config/config_test.go
internal/git/provider/provider.go
internal/server/polling/fake_git_provider_test.go
internal/server/polling/option.go
internal/server/polling/server.go
internal/server/polling/server_test.go
internal/server/polling/terraform.go

The test is very simple for now:
1. Creates some basic test resources.
2. Uses a fake k8s client.
3. Uses a fake git provider.
4. Starts the polling server.
5. Waits until the branch planner resource appears.
6. Creates a replan comment.
7. Waits until the branch planner resource has "reconcile" request
and placeholder comment id annotation.
8. Marks the pull request as closed.
9. Waits until the branch planner resource is deleted.
That covers the basic logic.
Discovered issues:
1. The isAllowedNamespace check was wrong.
2. The Source object can have nil Reference for branch.
I don't know what it does, I assume it uses a default branch, but we
didn't handle that.
Other changes:
1. I moved the `provider.FromURL` into a Server struct level field so we
can mock the provider layer. I tried to …

test: add test around the polling server and fix surfaced issues

---

tools/bump-libcrypto3-libssl3.sh

Simple usage:
```
❯ ./tools/bump-libcrypto3-libssl3.sh 3.1.4-r1
--> Old version: 3.1.4-r0
--> New version: 3.1.4-r1
Press ^C to exit or any key to continue...
```

chore(scripting): a simple script to bump libcrypto3 and libssl3 version

---

.github/dependabot.yaml

Changed dependabot schedule to weekly as we don't have to bump dependencies straight away unless they are security fixes.

chore: Only do security updates for Go modules and GH actions

---

internal/config/naming.go
internal/config/naming_test.go
internal/server/polling/poll_test.go
internal/server/polling/terraform.go

Issue
-----
When more than one Terraform resource points to the same git repository, when we clone the Source object, it does not create a new cloned Source object as the PullRequest ID is the same, the source name is the same, and we use only these two values to generate the name of the cloned resource.
Solution
--------
Add a short and deterministic hash to the name of the cloned Source object.
Another thoughts
----------------
It's not necessary to get a deterministic unique string, it could be random as we save the result as SourceRef. I decided to use a short (first 10 bytes of a sha256 hash), because if in the future we have to regenerate the values somehow, then we don't have to care about migration, extra compatibility checks. I know it's not likely we need this, but generating a …

fix: add unique hash to cloned source to avoid conflict

---

.github/workflows/helm-test.yaml

Part of a separate, more complex, PR[^1] I already bumped because it's failing in this state. It wasn't an issue for a while, but now it's failing on another PR[^2] as they changed helm files.
The error:
```
INFO: Downloading bootstrap version 'v2.0.0' of cosign to verify version to be installed...
https://storage.googleapis.com/cosign-releases/v2.0.0/cosign-linux-amd64
ERROR: Unable to validate cosign version: 'v2.0.0'
Error: Process completed with exit code 1.
```
[^1]: https://github.com/weaveworks/tf-controller/pull/1061/files#diff-b3c960a8ea0195d6eab8b2a10935ad64f1164f20953b4cc93adeec970ee3dbaaR31
[^2]: https://github.com/weaveworks/tf-controller/pull/1099

chore(deps): bump chart-testing-action to 2.6.1

---

docs/branch_planner/getting-started.md

The Getting Started guide described the default configuration wrong. When there is no ConfigMap, the Resources list is empty, as a result the Branch Planner doesn't check any namespaces.
Closes #1065
References:
- https://github.com/weaveworks/tf-controller/issues/1065

docs: update branch planner default configuration

---

.github/workflows/release.yaml
Makefile

Fix `make docker-build` target as it was missing a TARGETARCH build argument. Note that this is only used in local dev, CI uses the official docker GitHub actions to build the images.
Also noticed that the env var for LIBCRYPTO_VERSION was misplaced.

Fix `make docker-build` target

---

index.yaml

This should fix the Helm repository index.

moving Helm artefacts from weaveworks to tofu-controller

---

charts/tf-controller/README.md

Just a quick fix to the docs to try and help clean things up after the switch and help newcomers get started properly.

Update URL for Helm Docs

---

Makefile
charts/tf-controller/README.md
charts/tf-controller/README.md.gotmpl
charts/tf-controller/templates/packages.yaml
charts/tf-controller/values.yaml

This pr contains several updates to the helm chart:
- update image registry values to the new flux-iac organization
- update documentation metadata in chart to flux-iac pages
- update readme for the helm chart to contain these changes.
I havn't changed the chart version even though i think that would be the way to go. But since charts are currently linked to the controller versions i'll leave that up to the maintainers.
This solves the helm chart part of #1200

Helm chart url fixes

---

docs/use-tf-controller/build-and-use-a-custom-runner-image.md

updated following in the documentation:
- link to base image in ghcr (not yet available but ready for when it is)
- tf version to reflect the tf version there is used
- changed link to original dockerfile from a specific commit to main branch

updating documentation for custom runner

---

.github/workflows/e2e.yaml
Dockerfile
Makefile
config/branch-planner/kustomization.yaml
config/branch-planner/planner.yaml
config/default/kustomization.yaml
config/default/namespace.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/package/aws-package.yaml
config/samples/infra_v1alpha2_terraform.yaml
config/testdata/multi-tenancy/base/test.yaml
config/tilt/helm/dev-values.yaml
config/tilt/test/tf-dev-subject.yaml
local-e2e.sh

Rebranding/renaming to tofu-controller and flux-iac in /config
I've purposefully left service accounts alone, due to the way they are branded with kustomize resulting in also renaming the tf-runner accounts.
updated binary name in the docker file to tofu-controller.
Should fix #1215 and part of #1200

config yaml renaming and docker file binary renamed

---

tools/check-runner-images.sh

in regards to https://github.com/flux-iac/tofu-controller/issues/1200
renaming ghcr to flux-iac and added tf_version 1.5.7 to this tool

Renaming /tools/check-runner-images.sh

---

.github/workflows/scan.yaml
Dockerfile
planner.Dockerfile
runner-azure.Dockerfile
runner-base.Dockerfile

Fixes #1219 
There is a but attached to this though.
updating to alpine 3.19 seems to have updated packages to a python version that follows [https://peps.python.org/pep-0668/](pep-668) which enforces python virtual environments.
The current implemented solution is to add the --break-system-packages flag to the commands. This basically bypasses pep-668 and locale2e tests passes, but it might be good to consider moving it to virtual environments instead.

dockerfiles updated to alpine:3.19

---

controllers/tc000260_runner_pod_test.go
controllers/tf_controller_runner.go

Changes the default url for the runner images to point to the flux-iac registry in the go code and test.
This fixes 2 tasks in #1200

fallback ghcr urls changed to flux-iac in runner

---

.goreleaser.yml

This adds a Windows build for the CLI, and also reduces the resulting binary size by removing debug symbols.  The yield is about 30% reduction in size.

CLI: Reduce Binary Size

---

charts/tf-controller/templates/runner-serviceaccount.yaml

The end statement for the custom imagePullSecrets is wrongly placed af the bottom of the yaml file. Instead it should be placed at the end of the ServiceAccount definition.

Fix runner-serviceaccount helm template

---

DEVELOPMENT.md
Makefile

Closes https://github.com/flux-iac/tofu-controller/issues/1236

Update development docs

---

MAINTAINERS

Aksel Skaar Leirvaag has been a contributor from the early days of the project.
So, we are very happy to welcome Aksel (@akselleirv) as a new maintainer of Tofu-Controller 🎉 🎉
@akselleirv please
- approve this PR
- then merge it by yourself
Thank you and welcome to the team!

Add Aksel Skaar Leirvaag (@akselleirv) as a MAINTAINER

---

Tiltfile

Fix references to the old helm chart named `tf-controller` to the new name `tofu-controller`.

Tilt: fix references to helm chart after renaming

---

docs/branch-planner/branch-planner-getting-started.md
docs/use-tf-controller/provision-resources-with-customized-runner-pods.md
docs/use-tf-controller/upgrade-tf-controller.md

While learning about features of ~~tf~~ tofu-controller I found some broken links to weaveworks.github.io which inspired me to fix them.
Hope this helps someone.

docs: remove weaveworks.github.io references from docs

---

docs/use-tf-controller/with-a-custom-backend.md

Improve docs

---

controllers/tf_controller.go

Fixes: #1068
This PR addresses a bug in the Tofu Controller where the gotk_reconcile_condition metrics for the Ready condition were not being accurately reported, causing the metrics to perpetually show as updating even after a successful update.
Issue:
Post-update, the metrics incorrectly reported Unknown=1 with True/False=0, due to the misuse of the original terraform variable in a deferred function. This variable held the Unknown condition and inadvertently overwrote the correctly updated metrics.
Root Cause:
The defer statement used the original terraform variable, which contained the Unknown condition. This action overwrote the metrics that were updated correctly elsewhere in the code at a different point ([see here](https://github.com/weaveworks/tf-controller/blob/1958307fc83cc56f486 …

Fix Incorrect Metric Reporting Post-Update in Terraform Controller

---

cmd/manager/main.go
controllers/tf_controller.go
controllers/tf_controller_runner.go

The initial startup of a pod took atleast 15 seconds when waiting for an pod IP assignment. This change uses a watch on the pod instead of a polling mechanism which results in a much faster startup time. 
The only downside is that the clientset must be defined in the TerraformReconciler, however, the dependency is already existing. Improvement is noticeable in the e2e test where it perviously took 15 min where it now took 10 min.

Speedup wait for pod ip

---

charts/tofu-controller/README.md
charts/tofu-controller/templates/_helpers.tpl
charts/tofu-controller/values.yaml

Helm will still use "flux-system" namespace by default, but now the user can override it.
fixes #1286

Move hardcoded "flux-system" namespace from templates to default values

---

.github/dependabot.yaml

Tried to find out why non-security upgrades were turned off, but did not find any arguments in the [original PR](https://github.com/flux-iac/tofu-controller/pull/1145). 
I would assume it was due to noise? This might approve it a bit where we only get a maximum of three PRs with the new `directories` config in the dependabot.yml.

Enable non-security dependency upgrades

---

docs/use-tf-controller/with-tf-runner-logging.md
runner/server.go
runner/server_test.go

Closes #1296 
Example output after testing:
```
kubectl logs -n flux-system sensitive-output-test-tf-runner
2024/06/04 04:56:51 Starting the runner... version  sha
{"level":"info","ts":"2024-06-04T04:56:52.618Z","logger":"runner.terraform","msg":"preparing for Upload and Extraction","instance-id":""}
{"level":"info","ts":"2024-06-04T04:56:52.618Z","logger":"runner.terraform","msg":"write backend config","instance-id":"","path":"/tmp/flux-system-sensitive-output-test/sensitive-output-test","config":"backend_override.tf"}
{"level":"info","ts":"2024-06-04T04:56:52.618Z","logger":"runner.terraform","msg":"write config to file","instance-id":"","filePath":"/tmp/flux-system-sensitive-output-test/sensitive-output-test/backend_override.tf"} …
```

Print plan before apply

---

.github/workflows/build-and-publish.yaml
.github/workflows/release-runners.yaml
.github/workflows/release.yaml
Makefile
Tiltfile

The current version breaks the build: https://github.com/flux-iac/tofu-controller/actions/runs/9858437305/job/27219804027

bump libcrypto to 3.1.6-r2

---

charts/tofu-controller/templates/controller-serviceaccount.yaml
charts/tofu-controller/templates/deployment.yaml
charts/tofu-controller/templates/metrics-svc.yaml
charts/tofu-controller/templates/packages.yaml
charts/tofu-controller/templates/planner-deployment.yaml

When testing various deployment configuration with `helm template`, some resources did not have the expected namespace.

fix(helm-chart): ensure helm release namespace is applied

---

docs/tfctl.md

I needed it and discovered it works like a charm.

docs: provide instructions for autocomplete

---

api/v1alpha2/terraform_types.go
api/v1alpha2/terraform_types_test.go
api/v1alpha2/zz_generated.deepcopy.go
charts/tofu-controller/crds/crds.yaml
config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
docs/References/terraform.md

Added exponential backoff on reconciliation failure

---

cmd/tfctl/main.go
controllers/tf_controller.go
controllers/tf_controller_runner.go
internal/server/polling/terraform.go
tfctl/break_glass.go
tfctl/replan.go

Closes https://github.com/flux-iac/tofu-controller/issues/756

Fix deprecated usage of the k8s.io/apimachinery/pkg/util/wait package

---

README.md

While having a roadmap is great, circumstances have changed, and we can no longer commit to a specific timeline. It might be better to remove the roadmap for now.

README.md: remove roadmap

---

charts/tofu-controller/Chart.yaml
charts/tofu-controller/README.md
charts/tofu-controller/values.yaml
config/branch-planner/kustomization.yaml
config/manager/kustomization.yaml
docs/branch-planner/release.yaml
docs/release.yaml

Following the guide at https://github.com/flux-iac/tofu-controller/issues/1234#issuecomment-2358848473 and will then write a release process in a markdown.
Will release a new minor after letting the RC simmer for a few days.

Release v0.16.0-rc.5

---

.github/workflows/release.yaml
.goreleaser.yml
CHANGELOG.md

Also added the changelog which I forgot on the last attempt. 
Will need to create a new git tag due to [failing release pipeline](https://github.com/flux-iac/tofu-controller/actions/runs/12763702304/job/35574385787).

fix goreleaser flag in release workflow

---

docs/getting_started.md
docs/rc.yaml
docs/release.yaml

This PR fixes issue [#1508](https://github.com/flux-iac/tofu-controller/issues/1508)
Revised the YAML files used to install the latest release and RC release to install the renamed helm chart from what appears to be a new Helm chart repository.  Information was derived from the [manual installation instructions](https://flux-iac.github.io/tofu-controller/getting_started/#manual-installation).
```
#
#
kubectl apply -f docs/release.yaml
#
#
flux get helmreleases
NAME            REVISION        SUSPENDED       READY   MESSAGE                                                                                                  
tofu-controller 0.16.0-rc.5     False           True    Helm install succeeded for release flux-system/tofu-controller.v1 with chart tofu-controller@0.16.0-rc.5
``` …

Fix the HelmRelease scripts to install the latest helm chart

---

api/v1alpha2/terraform_types.go
charts/tofu-controller/crds/crds.yaml
config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
controllers/tf_controller_backend.go
docs/References/terraform.md
docs/use-tf-controller/control-init-upgrade.md
docs/use-tf-controller/index.md

The goal of this PR is control over the `init` process of a given stack. ATM this is hardcoded to `init -upgrade` which force updates all provioders within their smeVer ranges if one does not use fixed versions.
More background in the docs ;-)
- add new flag `upgradeOnInit` to API
- generate CRDs
- add documentation
---
PS: If the PR is approved, squash merge would be best strategy as the history contains an unnecessary step as well.

Control `init -upgrade` behaviour

---

.github/workflows/build-and-publish.yaml
.github/workflows/targeted-test.yaml
.github/workflows/test.yaml

The latest Ubuntu GitHub Action runners does not include the Terraform binary anymore: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
Therefore, overriding the Terraform binary no longer works, and we must instead copy the Terraform binary to PATH.

fix(ci): setup terraform

---

controllers/tc000012_src_ocirepository_no_outputs_test.go
controllers/tc000111_with_backend_s3_no_outputs_test.go
runner/server.go

This fix gathers the value for unlimited from the tar lib and passes it to the untar function to allow layer sizes bigger than the default of 100MB.
fixes #1511 as discussed.
Currently I did not implement tests. If this is wanted, I'll gladly add them if you would be okay with v1beta2 of `github.com/fluxcd/source-controller/api`.
I have this code running now with OCIs as big as 500MB for about 2 weeks. It is running flawless, I am really happy with this controller. Thanks for all the efforts, this makes a huge difference for me :-)
Thanks for your consideration.

fix(oci): allow unlimited layer size

---

go.mod
mtls/rotator.go

github.com/pkg/errors is archived due to being replaced by error wrapping support in the stdlib.
I also removed some dead code and some linting warnings.

Replace github.com/pkg/errors with errors wrapping using stdlib

---

docs/tfctl.md
mkdocs.yml

Hi and thanks for the project!
I found the references to the old repo a bit disturbing while browsing the docs.
So here is a small PR to change references to the actual repo.

Rename Weave GitOps to tofu-controller

---

docs/getting_started.md

Fixes broken github link in the getting-started documentation. `https://github.com/flux-iac/tofu-controller/tree/main/charts/tf-controller#tf-controller-for-flux` -> `https://github.com/flux-iac/tofu-controller/tree/main/charts/tofu-controller`

Fix broken github link
