- README.md
Update README to reflect changes for automatic `approvePlan`
> Update README for auto approvePlan

- README.md
- config/manager/manager.yaml
- config/rbac/cluster_role_binding.yaml
- config/rbac/kustomization.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/role_binding.yaml
- config/rbac/service_account.yaml
Fixes: #23 
Closes: #17 
Signed-off-by: Piaras Hoban <piaras@weave.works>
> feat: add specific ServiceAccount and update rbac w/same

- controllers/tc000201_auto_approve_with_disabled_drift_detection_test.go
- controllers/terraform_controller.go
Adds a full test for the situation where drift detection is disabled.
Resolves #24
> Full test scenario for `disableDriftDetection`

- .github/workflows/test.yaml
This PR adds a simple GitHub actions workflow to run tests against PR branches and on push to master
Resolves #35 
Makes sense to merge #42 first.
Signed-off-by: Piaras Hoban <piaras@weave.works>
> Github Actions workflow for tests

- Makefile
- api/v1alpha1/doc.go
- docs/api/terraform.md
- hack/api-docs/config.json
- hack/api-docs/template/members.tpl
- hack/api-docs/template/pkg.tpl
- hack/api-docs/template/type.tpl
This is to add make target to generate Terraform API spec documentation.
https://github.com/chanwit/tf-controller/issues/38
> Generate API documentation

- api/v1alpha1/doc.go
> Fix api groupName

- .github/workflows/test.yaml
- Dockerfile
> Upgrade Terraform to 1.1.4 and add GHA step for Terraform Setup

- README.md
Add documentation for managing Terraform state
Closes #15 
Signed-off-by: Piaras Hoban <piaras@weave.works>
> Document managing state

- MAINTAINERS
@phoban01 and @tomhuang12 
I need LGTM for both of you!
> create MAINTAINERS file

- Makefile
- go.mod
- go.sum
> Update source-controller to v0.21.1

- .github/workflows/scan.yaml
- Dockerfile
- Makefile
Trivy scans for vulnerabilities in container images.
> Add Trivy scan

- .github/workflows/release.yaml
- .github/workflows/scan.yaml
- Makefile
- config/manager/kustomization.yaml
- config/manager/manager.yaml
**What does this PR do**
This PR updates our Makefile and GitHub actions workflows to use the `ghcr.io/weaveworks` container registry.
> Image Registry Update

- Dockerfile
related to: https://github.com/weaveworks/tf-controller/issues/85
Signed-off-by: Filipe Sequeira <filipe@weave.works>
> Update Terraform to version 1.1.5

- README.md
- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
> fix image registry url on chart

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
- Makefile
- cmd/manager/main.go
- cmd/runner/main.go
- config/manager/manager.yaml
- config/rbac/kustomization.yaml
- config/rbac/runner_role.yaml
- config/rbac/runner_role_binding.yaml
- config/rbac/service_account.yaml
- controllers/suite_test.go
- controllers/terraform_controller.go
- local-e2e.sh
- mtls/runner_serve.go
- runner.Dockerfile
This PR implements TF-runner pod invocation, and the main runner program.
Fix #70 #71 and #73
> implement tf-runner pod and main program

- controllers/terraform_controller.go
> Exponentially increase wait time for runner pod

- config/manager/kustomization.yaml
- runner.Dockerfile
> bump version to 0.9.0-rc.3

- charts/tf-controller/Chart.yaml
- charts/tf-controller/templates/_helpers.tpl
> chart: set default runner sa to be tf-runner

- .github/workflows/e2e.yaml
- controllers/terraform_controller.go
This PR gives a block of 10 secs before gRPC going connection timed out.
> use retry policy for grpc connection

- charts/tf-controller/Chart.yaml
- charts/tf-controller/templates/crds.yaml
- charts/tf-controller/values.yaml
- Add new attribute to CRD
- Bump chart version to v0.1.6
- Bump controller and runner version to v0.9.0-rc.4
> update chart for v0.9.0-rc.4

- controllers/terraform_controller.go
- mtls/rotator.go
Signed-off-by: Piaras Hoban <phoban01@gmail.com>
> Fix secret label scoping

- Makefile
- go.mod
- go.sum
> update source controller to v0.21.2

- .github/workflows/e2e.yaml
- runner.Dockerfile
This PR upgrades the Terraform binary to v1.1.7.
Fixes #157
> upgrade terraform binary to 1.1.7

- Dockerfile
- runner.Dockerfile
Fixes https://github.com/weaveworks/tf-controller/issues/175
> fix CVE-2022-0778

- CHANGELOG.md
- config/manager/kustomization.yaml
> Changelog for v0.9.0 

- controllers/terraform_controller.go
There's a race condition that the old runner pod is being terminated, while the reconciler starts a new loop. So it looks up and finds the old pod, then the process is broken.
This PR is trying to fix this condition by waiting for the old pod to be completely terminated before doing anything else.
> wait for runner pod to completely terminate

- controllers/terraform_controller.go
fix the error: failed to wait for the terminating runner pod
> Fix runner pod creation

- controllers/terraform_controller.go
Fix getting runner pod logic.
Use `var runnerPod corev1.Pod` instead of  `*corev1.Pod`.
Fixes #183
> Fix runner pod pointer

- .github/workflows/scan.yaml
- Dockerfile
- runner.Dockerfile
> Update base image to alpine 3.15.3

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/controller-serviceaccount.yaml
- charts/tf-controller/templates/deployment.yaml
- charts/tf-controller/templates/runner-serviceaccount.yaml
> Use imagePullSecrets on ServiceAccounts

- controllers/tc000010_no_outputs_test.go
- controllers/tc000012_src_bucket_no_outputs_test.go
- controllers/tc000030_plan_only_no_outputs_test.go
- controllers/tc000050_plan_and_manual_approve_no_outputs_test.go
- controllers/tc000051_plan_and_manual_approve_and_replan_no_outputs_test.go
- controllers/tc000100_applied_should_tx_to_plan_when_source_changed_test.go
- controllers/tc000110_auto_applied_should_tx_to_plan_then_apply_when_source_changed_test.go
- controllers/tc000121_destroy_on_delete_test.go
- controllers/tc000130_destroy_no_outputs_test.go
- controllers/tc000140_auto_applied_should_tx_to_plan_then_apply_when_drift_detected_test.go
- controllers/tc000150_manual_apply_should_report_and_loop_when_drift_detected_test.go
- controllers/tc000160_auto_applied_should_tx_to_plan_when_unrelated_source_changed_test.go
- controllers/tc000220_support_config_file_via_secret_test.go
- runner/server.go
Closes #204 
Also moved a couple of `consts` out from function scope and into package scope as their values were used in a few places.
> Swap from Label to Annotation

- .github/workflows/release.yaml
- .goreleaser.yml
**What do this PR do?**
This PR adds configures [GoReleaser](https://goreleaser.com/intro/) to manage releases.
Fixes #197 
Signed-off-by: Piaras Hoban <phoban01@gmail.com>
> Use GoReleaser for releases

- cmd/manager/main.go
> fix the nil reference for event recorder

- Makefile
> revert back to go get as go install currently breaks e2e

- controllers/terraform_controller.go
> re-arrange logging to fix nil reference for writeBackendConfig

- api/v1alpha1/terraform_types.go
- charts/tf-controller/Chart.yaml
- charts/tf-controller/templates/crds.yaml
- config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
- controllers/tc000260_runner_pod_test.go
- controllers/tc000280_inventory_test.go
- controllers/terraform_controller.go
- docs/References/terraform.md
- runner/server.go
> implement enableInventory flag

- controllers/tc000140_auto_applied_should_tx_to_plan_then_apply_when_drift_detected_test.go
> fix test 140 - add an or predicate

- Dockerfile
- config/manager/manager.yaml
- controllers/terraform_controller.go
- runner.Dockerfile
> improve security via security context of controller and runner

- charts/tf-controller/Chart.yaml
- charts/tf-controller/templates/deployment.yaml
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
- controllers/terraform_controller.go
- mtls/grpc.go
- mtls/rotator.go
> use channel to trigger cert rotation

- controllers/tc000260_runner_pod_test.go
- controllers/terraform_controller.go
- local-e2e.sh
- mtls/rotator.go
This PR fixes pod reconciliation when restarting the TF-controller.
> fix pod reconciliation

- charts/tf-controller/Chart.yaml
- charts/tf-controller/templates/deployment.yaml
- charts/tf-controller/values.yaml
- cmd/manager/main.go
- controllers/tc000260_runner_pod_test.go
- controllers/terraform_controller.go
> Stabilizing the controller under high loads

- config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
- config/rbac/role.yaml
Signed-off-by: Luke Mallon (Nalum) <luke.mallon@weave.works>
> Add missing entry in rbac and crd

- charts/tf-controller/Chart.yaml
- charts/tf-controller/templates/deployment.yaml
- charts/tf-controller/values.yaml
- cmd/manager/main.go
- cmd/runner/main.go
- controllers/suite_test.go
- controllers/terraform_controller.go
- mtls/runner_serve.go
> make the grpc max message size configurable

- api/v1alpha1/terraform_types.go
- controllers/terraform_controller.go
> revisit ready status

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
> bump version to v0.13.0-rc.1

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/crds.yaml
> update helm chart to v0.13.0-rc.1

- controllers/terraform_controller.go
> add info log for webhooks

- api/v1alpha1/terraform_types.go
- config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
- docs/References/terraform.md
- docs/use_cases.md
- Added runner pod spec docs
- Added force-unlock docs
> Docs update for new features

- docs/use_cases.md
> fix the quotes bugs in the docs

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/crds.yaml
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
- docs/getting_started.md
- docs/index.md
- docs/rc.yaml
> prepare for v0.13.0-rc.2

- Makefile
- docs/getting_started.md
- docs/index.md
> doc: fix preflight checks

- runner-azure.Dockerfile
> Add runner dockerfile for azure

- .github/workflows/test.yaml
> move tests to be after image push

- .github/workflows/release.yaml
> upgrade goreleaser action

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
- docs/rc.yaml
> bump chart to use v0.13.0-rc.5 image

- .github/workflows/e2e.yaml
> fix make dev-deploy for e2e

- controllers/tf_controller_outputs.go
- runner/server.go
> re-implement input references with template

- controllers/tf_controller.go
> check output secret of the dependencies

- controllers/tc000241_auto_approve_with_health_checks_test.go
- controllers/tc000340_webhooks_for_post_planning_test.go
- controllers/tc000350_depends_on_test.go
- controllers/tf_controller.go
- controllers/tf_controller_health_checks.go
- controllers/tf_controller_webhooks.go
- docs/use_tf_controller/to_provision_Terraform_resources_that_are_required_health_checks.md
- docs/use_tf_controller/with_GitOps_dependency_management.md
- runner/server.go
> add a test for dependency management

- runner/server.go
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>
> Fix workspace new logging

- charts/tf-controller/Chart.yaml
- charts/tf-controller/templates/crds.yaml
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
> bump chart to v0.8.4

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
> bump chart to v0.8.5

- .github/workflows/test.yaml
- controllers/tf_controller.go
- controllers/tf_controller_backend.go
> add labels to k8s backend and split tests

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
> bump chart to v0.8.6 and image to v0.13.0-rc.10

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/packages.yaml
- charts/tf-controller/values.yaml
Fixes https://github.com/weaveworks/tf-controller/issues/408
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>
> Parameterize aws-package in chart

- docs/use_tf_controller/to_provision_resources_and_destroy_them_when_the_Terraform_object_gets_deleted.md
> Just a little typo

- controllers/tc000051_plan_and_manual_approve_and_replan_no_outputs_test.go
- controllers/tf_controller.go
> implement replan with commit id

- Makefile
- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
- cmd/manager/main.go
- cmd/runner/main.go
- config/manager/kustomization.yaml
> add sha and version to binaries

- CHANGELOG.md
- docs/release.yaml
> prepare changelog for v0.13

- .github/workflows/release.yaml
- .github/workflows/scan.yaml
- Makefile
- runner-azure.Dockerfile
Update various CI actions to include tf-runner-azure image
> Update various CI actions to include tf-runner-azure image

- docs/getting_started.md
> docs: bump version to v0.13.0 in the getting started guide

- CHANGELOG.md
- README.md
- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
- docs/getting_started.md
- docs/index.md
- docs/release.yaml
- docs/use_tf_controller/with_GitOps_dependency_management.md
> docs and chart for v0.13.1

- Dockerfile
- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/packages.yaml
- charts/tf-controller/values.yaml
- config/package/aws-package.yaml
- docs/release.yaml
- docs/use_tf_controller/with_GitOps_dependency_management.md
- docs/use_tf_controller/with_the_ready_to_use_AWS_package.md
- runner.Dockerfile
> update aws package and add metadata

- docs/use_tf_controller/index.md
- docs/use_tf_controller/with_the_ready_to_use_AWS_package.md
> improve aws doc

- controllers/tc000280_inventory_test.go
- controllers/tf_controller_apply.go
- controllers/tf_controller_reconcile.go
> fix inventory in case of missing

- docs/index.md
- docs/use_tf_controller/to_force_unlock_Terraform_states.md
- docs/use_tf_controller/to_provision_resources_and_destroy_them_when_the_Terraform_object_gets_deleted.md
Small PR to get promoted from "first-time contributor" status
> minor docs fixes: typos and deadlinks

- controllers/tf_controller_apply.go
> Force replan if cannot load tfplan correctly

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/crds.yaml
> update crd fields and bump helm chart

- api/go.mod
- api/go.sum
- api/v1alpha1/terraform_types.go
- api/v1alpha1/trim_str_test.go
- controllers/tf_controller_apply.go
> refactor message-related functions

- .github/workflows/release.yaml
- .github/workflows/scan.yaml
- Dockerfile
- runner-azure.Dockerfile
- runner.Dockerfile
Update Dockerfiles and pipelines to build multi-arch variants of images
> add support for building multi-arch docker images

- .github/workflows/test.yaml
I missed this file in #514.  It will help with pre-release testing, but won't provide any production value.
Feel free to close if this is deemed unnecessary.
> update test images to build for multi platforms

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/crds.yaml
- docs/rc.yaml
Fixes #534
- bump chart version to v0.10.3
- use v0.14.0-rc.6 image
> bump helm chart to v0.10.3 and update rc.yaml

- api/v1alpha1/terraform_types.go
> change the default of retryInterval to 15s

- .github/workflows/release.yaml
- CHANGELOG.md
- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/crds.yaml
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
- docs/rc.yaml
bump helm chart to v0.15.0-rc.1
> bump helm chart to v0.15.0-rc.1

- .github/workflows/e2e.yaml
- config/testdata/gc-old-certs/test.yaml
- docs/References/terraform.md
- mtls/grpc.go
- mtls/rotator.go
> implement garbage collecting old cert secrets

- controllers/tf_controller_runner.go
Corrected inteval to interval in trace logs
> fix typo in tf_controller_runner.go

- Tiltfile
- config/tilt/test/tf-dev-subject.yaml
- controllers/tc000075_varsfrom_secret_with_varkeys_rename_and_controlled_outputs_test.go
- runner/server.go
- runner/server_generate_tf_vars.go
- runner/server_generate_tf_vars_test.go
- runner/server_outputs.go
> add renaming for varsFrom keys

- .goreleaser.yml
- api/v1alpha2/terraform_types.go
- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/templates/deployment.yaml
- charts/tf-controller/values.yaml
- cmd/manager/main.go
- config/tilt/manager/patch.yaml
- controllers/suite_test.go
- controllers/tf_controller.go
- controllers/tf_controller_runner.go
- mtls/rotator.go
> allow passing cluster-domain (default: cluster.local)

- .github/workflows/helm-test.yaml
- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/ci/test-values.yaml
- charts/tf-controller/ci/test_values.yaml
- charts/tf-controller/values.yaml
- config/manager/kustomization.yaml
- runner/server.go
- runner/server_plan.go
- runner/server_save_tfplan.go
- runner/server_show_plan.go
This PR bumps chart version to v0.14.3 and fixes a logging issue.
> Bump chart v0.14.3 fix logging

- Dockerfile
- cmd/manager/main.go
- controllers/tf_controller.go
- planner.Dockerfile
- runner-azure.Dockerfile
- runner.Dockerfile
Fixes #639 
Result to confirm the fix:
```
$ curl -vvvv http://localhost:8080/metrics
certwatcher_read_certificate_errors_total 0
certwatcher_read_certificate_total 0
controller_runtime_active_workers{controller="terraform"} 1
controller_runtime_max_concurrent_reconciles{controller="terraform"} 4
controller_runtime_reconcile_errors_total{controller="terraform"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="terraform",le="0.005"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="terraform",le="0.01"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="terraform",le="0.025"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="terraform",le="0.05"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="terraform",le="0.1"} 0 …
```
> Fix broken metrics

- runner/server_outputs.go
Fixes #649
This PR is required to backport to v0.14.4.
Note: Trivy scan will be addressed later when Alpine ships the new libssl3 / libcrypto3 packages.
> fix logging for tf.output

- Dockerfile
- controllers/tf_controller_runner.go
- planner.Dockerfile
- runner-azure.Dockerfile
- runner.Dockerfile
Fixes #531 #481 
Also, Fixes #659 
Fix per observation from #531.
> honor pod grace period seconds in case of controller restart

- cmd/branch-based-planner/main.go
- internal/server/polling/server.go
Fixes #671.
* Simplify main.go by using a single goroutine and a single context
* Use a time.Ticker instead of time.Sleep, to avoid blocking for `>=pollingInterval` before exiting
(More commentary in the commit messages. Apologies for the branch name.)
> Minor concurrency fixes in branch-based planner

- cmd/branch-based-planner/README.md
This adds a README under cmd/branch-based-planner, telling you how to set things up so it'll run and give some result.
> Instructions for running the branch-based-planner

- controllers/tf_controller.go
> add finalizer to the dep only if object is not being deleted

- docs/adr/0000-template.md
- docs/adr/0000-use-adrs-for-decisions.md
- docs/adr/0001-pr-polling-workflow.md
Status will be updated when it's accepted.
Added an ADR to document the decision we use ADRs and linked some docs about it.
closes #682
> docs: document ADR about polling, workflow, and responsibilities

- rfcs/0001-polling-mechanism/README.md
Follow-up #607 
Fixes #623
Address two questions:
- configuration options
- pod restart & in-memory storage
> address comments for RFC-0001

- DEVELOPMENT.md
- api/v1alpha2/terraform_types.go
- config/crd/bases/infra.contrib.fluxcd.io_terraforms.yaml
- config/tilt/test/tf-dev-subject.yaml
- controllers/source_predicate.go
- controllers/tc000044_plan_only_mode_test.go
- controllers/tf_controller.go
- controllers/tf_controller_apply.go
- controllers/tf_controller_reconcile.go
- docs/References/terraform.md
If `planOnly` is `true`, never apply terraform changes.
closes #670
> feat: add PlanOnly mode

- .github/workflows/build-and-publish.yaml
> feat: build and publish images GitHub workflow

- .github/workflows/test.yaml
Closes #698
merge only after #702
> patch: don't build and publish images in the test workflow

- Dockerfile
- controllers/tf_controller.go
- runner-azure.Dockerfile
- runner.Dockerfile
> [v0.14] add finalizer to the dep only if object is not being deleted

- docs/branch_based_planner/least-required-permissions.md
> docs: least required permissions for a github api token

- docs/index.md
- docs/use_tf_controller/logging_env_variables.md
- docs/use_tf_controller/to_plan_and_manually_apply_Terraform_resources.md
- docs/use_tf_controller/to_provision_resources_and_auto_approve.md
Moves content from WW user docs to complementary pages per @yiannistri's suggestion and updates a descriptive word in the Overview page.
> Changes to user docs

- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
- config/bbp/kustomization.yaml
- config/manager/kustomization.yaml
- docs/release.yaml
> bump helm chart to v0.15.0

- README.md
- api/v1alpha2/groupversion_info.go
- docs/getting_started.md
- docs/how_to/index.md
- docs/how_to/troubleshooting_with_break_the_glass_mode.md
- docs/index.md
- docs/tfctl.md
- docs/use_tf_controller/index.md
- docs/use_tf_controller/to_detect_drifts_only_without_plan_or_apply.md
- docs/use_tf_controller/to_force_unlock_Terraform_states.md
- docs/use_tf_controller/to_plan_and_manually_apply_Terraform_resources.md
- docs/use_tf_controller/to_provision_Terraform_resources_that_are_required_health_checks.md
- docs/use_tf_controller/to_provision_resources_and_auto_approve.md
- docs/use_tf_controller/to_provision_resources_and_destroy_them_when_the_Terraform_object_gets_deleted.md
- docs/use_tf_controller/to_provision_resources_and_obtain_outputs.md
- docs/use_tf_controller/to_provision_resources_with_customized_Runner_Pods.md
- docs/use_tf_controller/to_set_variables_for_Terraform_resources.md
- docs/use_tf_controller/with_GitOps_dependency_management.md
- docs/use_tf_controller/with_Terraform_Enterprise.md
- docs/use_tf_controller/with_a_custom_backend.md
- docs/use_tf_controller/with_an_OCI_Artifact_as_Source.md
- docs/use_tf_controller/with_drift_detection_disabled.md
- docs/use_tf_controller/with_primitive_modules.md
- docs/use_tf_controller/with_tf_runner_logging.md
- docs/use_tf_controller/with_the_ready_to_use_AWS_package.md
> update docs for v0.15.0

- CHANGELOG.md
- charts/tf-controller/Chart.yaml
- charts/tf-controller/README.md
- charts/tf-controller/values.yaml
- config/bbp/kustomization.yaml
- config/manager/kustomization.yaml
- docs/release.yaml
- tools/bump-version.sh
> write changelog and bump helm chart for v0.15.1

- internal/informer/branch-planner/comment.tpl
Closes #753
Closes #752
References:
* https://github.com/weaveworks/tf-controller/issues/753
* https://github.com/weaveworks/tf-controller/issues/752
> patch: use hcl syntax and don't use <details> tag for plan output in comments

- .github/dependabot.yaml
> add dependabot.yaml

- controllers/tc000042_output_name_contains_dot_test.go
- docs/how_to/troubleshooting_with_break_the_glass_mode.md
- docs/use_tf_controller/to_set_variables_for_Terraform_resources.md
- docs/use_tf_controller/with_the_ready_to_use_AWS_package.md
> improve renaming variable docs

- .github/workflows/test.yaml
- api/v1alpha2/terraform_types.go
- controllers/tf_controller.go
- controllers/tf_controller_finalizer.go
closes #585 
- Add RecordDuration metrics and uses functions from fluxcd package dropping the custom Record functions.
> Add RecordDuration metrics and using functions from fluxcd

- internal/informer/branch-planner/informer.go
On `!replan` we post a "please wait" placeholder comment and save the comment id on the Terraform object. When we see a new plan with the informer we check if comment id is defined or not. If it's defined, Informer updates that comment with the plan, otherwise creates a new comment.
That annotation was never cleared so after a `!replan`, all plan outputs in the future will be just an update on that comment.
Closes #802
References:
* https://github.com/weaveworks/tf-controller/issues/802
> fix: clear comment id after replan

- charts/tf-controller/README.md
- charts/tf-controller/templates/planner-deployment.yaml
- charts/tf-controller/values.yaml
- runner-azure.Dockerfile
Additional changes:
* Removed 8080 http port, it was the remamining of the webhook based system.
Closes #806 
References:
* https://github.com/weaveworks/tf-controller/issues/806
> feat: ability to set resource limits and security context for branch planner

- internal/server/polling/terraform.go
> fix output secret relocation for branch planner

- docs/branch_planner/getting-started.md
- docs/branch_planner/index.md
- mkdocs.yml
Added section in docs for Branch Planner.
Closes #798
> docs: Add Branch Planner guide

- docs/how_to/flux_receiver_and_alert.md
- docs/how_to/index.md
> Add Flux Receiver and Alert integration doc

- internal/server/polling/terraform.go
Fixes #876 
To integrate Terraform Cloud with the Branch Planner through a Terraform Custom Resource (CR), it's required that the planning occurs locally within the cluster. To achieve this:
1. Remove the cloud configuration block.
2. Remove the `tfrc` credentials.
By implementing these modifications, we can ensure smooth integration of the Branch Planner with Terraform Cloud.
> small fix for branch planner to support terraform cloud

- README.md
PR makes the badge status appear. Partly fixes #859.
> Adds OpenSSF badge to Readme

- SECURITY.md
> doc: Add SECURITY.md

- controllers/cleaner_test.go
- controllers/tc000012_src_bucket_no_outputs_test.go
- controllers/tc000013_source_not_found_test.go
- controllers/tc000014_artifact_not_found_test.go
- controllers/tc000016_finilize_status_test.go
- controllers/tc000030_plan_only_no_outputs_test.go
- controllers/tc000031_plan_only_with_showplan_as_cm_no_outputs_test.go
References:
* https://github.com/weaveworks/tf-controller/issues/920
Fixes #920
> fix: 000031 test and add more safe defer cleanup

- controllers/tc000070_varsfrom_secret_and_controlled_outputs_test.go
- controllers/tc000071_varsfrom_secret_with_varkeys_and_controlled_outputs_test.go
- controllers/tc000072_varsfrom_optional_secret_controlled_outputs_test.go
- controllers/tc000073_varsfrom_accepts_many_secrets_outputs_test.go
- controllers/tc000074_varsfrom_accepts_many_secrets_with_last_supplied_key_precedence_test.go
- controllers/tc000075_varsfrom_secret_with_varkeys_rename_and_controlled_outputs_test.go
```
❯ go test ./controllers -parallel=1 -count=3 -test.run=Test_00007
ok      github.com/weaveworks/tf-controller/controllers 68.527s
```
Fixes #907
References:
* https://github.com/weaveworks/tf-controller/issues/907
> fix: controller 7x tests

- controllers/cleaner_test.go
- controllers/tc000140_auto_applied_should_tx_to_plan_then_apply_when_drift_detected_test.go
- controllers/tc000150_manual_apply_should_report_and_loop_when_drift_detected_test.go
- controllers/tc000160_auto_applied_should_tx_to_plan_when_unrelated_source_changed_test.go
- controllers/tc000170_if_apply_error_we_should_delete_the_plan_and_start_over_test.go
```
❯ go test ./controllers -parallel=1 -count=1 -test.run="Test_0001[4567]"
ok      github.com/weaveworks/tf-controller/controllers 80.345s
```
Fixes #946
References:
* https://github.com/weaveworks/tf-controller/issues/946
> fix: controller 1xx tests

- charts/tf-controller/README.md
- charts/tf-controller/templates/deployment.yaml
- charts/tf-controller/templates/planner-deployment.yaml
- charts/tf-controller/values.yaml
.. so people using the chart can switch them back on, if they must.
Addresses #324.
> Expose --allow-cross-namespace-refs in the chart

- Makefile
This PR adds `tools` target to the Makefile.
> add tools target for the makefile

- controllers/tc000290_force_unlock_test.go
> fix controllers/tc00029x tests

- .github/workflows/release.yaml
> add base image to the release pipeline

- .github/workflows/docs.yaml
- .github/workflows/helm-release.yaml
- .github/workflows/helm-test.yaml
- .github/workflows/ossf.yaml
- .github/workflows/release.yaml
- .github/workflows/scan.yaml
> ci: Pinned GH actions to commit hashes

- .github/workflows/build-and-publish.yaml
- .github/workflows/release-runners.yaml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
- planner.Dockerfile
- runner-base.Dockerfile
Versioning of the two packages are the same, it's annoying to update all dockerfiles, now they are an ARG to the dockerfile and it's enough to update in the Makefile.
> chore(deps): update libcrypto3 and libssl3

- docs/how_to/upgrade-tf-controller.md
Page added by user request. Steps reviewed and updated by @madAndroid.
> Adds page on upgrading TF-Controller

- docs/how_to/resource_deletion.md
> docs: Document a fix to "terraform objects stuck on deletion" issue

- README.md
Adds a "get in touch" section to the Readme with info about the project Slack channel and a tip to file issues.
> Adds Slack channel info to Readme

- docs/how_to/build-and-use-a-custom-runnner-image.md
- Follows the process outlined by @chanwit in https://github.com/tf-controller/tf-runner-images
> Add docs on how to build a custom runner image

- .github/workflows/build-and-publish.yaml
- runner-base.Dockerfile
~WIP, and needs testing, but should~ Fixes #1057
> Fix missing version and sha in runner output

- docs/use_tf_controller/with_plan_only_mode.md
Missed this from previous PR. Text search did not yield any more results.
> docs: Fix API version

- docs/use_tf_controller/with-ipv6.md
> docs: add docs about ipv6

- controllers/tc000243_remediation_retry_test.go
Resolves #1149
References:
- https://github.com/weaveworks/tf-controller/issues/1149
> test: add test case to remediation test: retry resets when source is updated

- docs/use_tf_controller/with-azure.md
Closes #561, with content provided by the users. This is just a starter page for the topic to close the issue.
> Adds a starter docs page on Azure

- mkdocs.yml
Some files were renamed so we need to also update the navigation.
> docs: Fix navigation

- MAINTAINERS
This project grew on my heart and I intend to take care of it long term.
> I volunteer to be a maintenance

- .github/workflows/build-and-publish.yaml
- .github/workflows/helm-release.yaml
- .github/workflows/release-runners.yaml
- .github/workflows/release.yaml
- .github/workflows/scan.yaml
> replace container reg ghcr.io/weaveworks with ghcr.io/flux-iac

- runner.Dockerfile
this pr contains the update for the tf binary to 1.5.7
> updating tf_version

- Makefile
This fixes Makefile part of #1200.
I havn't tested this fully yet, so making this as a draft PR for now as it might have unforseen side effects.
will do some testing during today and see what happens.
> move urls from weave to flux-iac in makefile

- Tiltfile
The tf-runner image was only built but not used in the helloworld-tf Terraform example. With this change the Terraform spec will be updated by Tilt with the tag which was produced by `docker_build`.
> Tiltfile: added config for building tf-runner image and using it in helloworld example

- MAINTAINERS
We welcome Tonni Follmann (@ilithanos) as a maintainer of the Tofu-Controller project :tada: :tada: 
@ilithanos please
- approve this PR
- then merge it by yourself
Thank you and welcome to the team!
> Add Tonni Follmann (@ilithanos) as a MAINTAINER

- .dockerignore
- Dockerfile.dev
- Tiltfile
- planner.Dockerfile.dev
- runner.Dockerfile.dev
Closes https://github.com/flux-iac/tofu-controller/issues/1225
> tilt: speed up compiling of binaries

- charts/tofu-controller/README.md
- charts/tofu-controller/README.md.gotmpl
- charts/tofu-controller/templates/metrics-svc.yaml
- charts/tofu-controller/templates/runner-discovery-service.yaml
Closes https://github.com/flux-iac/tofu-controller/issues/1280
> fix(helm-chart): missing renamings
